/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as PayRouteImport } from './routes/pay'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RecoverRouteImport } from './routes/recover'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminReconciliationRouteImport } from './routes/admin.reconciliation'
import { Route as AdminScanRouteImport } from './routes/admin.scan'
import { Route as TicketIndexRouteImport } from './routes/ticket.index'
import { Route as TicketCodeRouteImport } from './routes/ticket.$code'
import { Route as TicketDemoRouteImport } from './routes/ticket.demo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverRoute = RecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReconciliationRoute = AdminReconciliationRouteImport.update({
  id: '/reconciliation',
  path: '/reconciliation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScanRoute = AdminScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AdminRoute,
} as any)
const TicketIndexRoute = TicketIndexRouteImport.update({
  id: '/ticket/',
  path: '/ticket/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketCodeRoute = TicketCodeRouteImport.update({
  id: '/ticket/$code',
  path: '/ticket/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketDemoRoute = TicketDemoRouteImport.update({
  id: '/ticket/demo',
  path: '/ticket/demo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/affiliate': typeof AffiliateRoute
  '/admin': typeof AdminRouteWithChildren
  '/affiliate': typeof AffiliateRoute
  '/checkout': typeof CheckoutRoute
  '/pay': typeof PayRoute
  '/privacy': typeof PrivacyRoute
  '/recover': typeof RecoverRoute
  '/scanner': typeof ScannerRoute
  '/terms': typeof TermsRoute
  '/tickets': typeof TicketsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reconciliation': typeof AdminReconciliationRoute
  '/admin/scan': typeof AdminScanRoute
  '/ticket/$code': typeof TicketCodeRoute
  '/ticket/demo': typeof TicketDemoRoute
  '/ticket/': typeof TicketIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/affiliate': typeof AffiliateRoute
  '/admin': typeof AdminRouteWithChildren
  '/affiliate': typeof AffiliateRoute
  '/checkout': typeof CheckoutRoute
  '/pay': typeof PayRoute
  '/privacy': typeof PrivacyRoute
  '/recover': typeof RecoverRoute
  '/scanner': typeof ScannerRoute
  '/terms': typeof TermsRoute
  '/tickets': typeof TicketsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reconciliation': typeof AdminReconciliationRoute
  '/admin/scan': typeof AdminScanRoute
  '/ticket/$code': typeof TicketCodeRoute
  '/ticket/demo': typeof TicketDemoRoute
  '/ticket': typeof TicketIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/affiliate': typeof AffiliateRoute
  '/admin': typeof AdminRouteWithChildren
  '/affiliate': typeof AffiliateRoute
  '/checkout': typeof CheckoutRoute
  '/pay': typeof PayRoute
  '/privacy': typeof PrivacyRoute
  '/recover': typeof RecoverRoute
  '/scanner': typeof ScannerRoute
  '/terms': typeof TermsRoute
  '/tickets': typeof TicketsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reconciliation': typeof AdminReconciliationRoute
  '/admin/scan': typeof AdminScanRoute
  '/ticket/$code': typeof TicketCodeRoute
  '/ticket/demo': typeof TicketDemoRoute
  '/ticket/': typeof TicketIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/affiliate'
    | '/admin'
    | '/affiliate'
    | '/checkout'
    | '/pay'
    | '/privacy'
    | '/recover'
    | '/scanner'
    | '/terms'
    | '/tickets'
    | '/admin/login'
    | '/admin/reconciliation'
    | '/admin/scan'
    | '/ticket/$code'
    | '/ticket/demo'
    | '/ticket/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/affiliate'
    | '/admin'
    | '/affiliate'
    | '/checkout'
    | '/pay'
    | '/privacy'
    | '/recover'
    | '/scanner'
    | '/terms'
    | '/tickets'
    | '/admin/login'
    | '/admin/reconciliation'
    | '/admin/scan'
    | '/ticket/$code'
    | '/ticket/demo'
    | '/ticket'
  id:
    | '__root__'
    | '/'
    | '/affiliate'
    | '/admin'
    | '/affiliate'
    | '/checkout'
    | '/pay'
    | '/privacy'
    | '/recover'
    | '/scanner'
    | '/terms'
    | '/tickets'
    | '/admin/login'
    | '/admin/reconciliation'
    | '/admin/scan'
    | '/ticket/$code'
    | '/ticket/demo'
    | '/ticket/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AffiliateRoute: typeof AffiliateRoute
  AdminRoute: typeof AdminRouteWithChildren
  AffiliateRoute: typeof AffiliateRoute
  CheckoutRoute: typeof CheckoutRoute
  PayRoute: typeof PayRoute
  PrivacyRoute: typeof PrivacyRoute
  RecoverRoute: typeof RecoverRoute
  ScannerRoute: typeof ScannerRoute
  TermsRoute: typeof TermsRoute
  TicketsRoute: typeof TicketsRoute
  TicketCodeRoute: typeof TicketCodeRoute
  TicketDemoRoute: typeof TicketDemoRoute
  TicketIndexRoute: typeof TicketIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover': {
      id: '/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof RecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reconciliation': {
      id: '/admin/reconciliation'
      path: '/reconciliation'
      fullPath: '/admin/reconciliation'
      preLoaderRoute: typeof AdminReconciliationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scan': {
      id: '/admin/scan'
      path: '/scan'
      fullPath: '/admin/scan'
      preLoaderRoute: typeof AdminScanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/ticket/': {
      id: '/ticket/'
      path: '/ticket'
      fullPath: '/ticket/'
      preLoaderRoute: typeof TicketIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$code': {
      id: '/ticket/$code'
      path: '/ticket/$code'
      fullPath: '/ticket/$code'
      preLoaderRoute: typeof TicketCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/demo': {
      id: '/ticket/demo'
      path: '/ticket/demo'
      fullPath: '/ticket/demo'
      preLoaderRoute: typeof TicketDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminReconciliationRoute: typeof AdminReconciliationRoute
  AdminScanRoute: typeof AdminScanRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminReconciliationRoute: AdminReconciliationRoute,
  AdminScanRoute: AdminScanRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AffiliateRoute: AffiliateRoute,
  AdminRoute: AdminRouteWithChildren,
  AffiliateRoute: AffiliateRoute,
  CheckoutRoute: CheckoutRoute,
  PayRoute: PayRoute,
  PrivacyRoute: PrivacyRoute,
  RecoverRoute: RecoverRoute,
  ScannerRoute: ScannerRoute,
  TermsRoute: TermsRoute,
  TicketsRoute: TicketsRoute,
  TicketCodeRoute: TicketCodeRoute,
  TicketDemoRoute: TicketDemoRoute,
  TicketIndexRoute: TicketIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
